name: stream_test_scheduler
description: A starting point for Dart libraries or applications.
version: 0.1.0
author: Michael Maier <maier1michael@gmail.com>
homepage: https://github.com/maiermic/stream_test_scheduler

environment:
  sdk: '>=1.8.3 <2.0.0'

dependencies:
  matcher: ^0.12.0

dev_dependencies:
  stream_ext: ^0.4.0
  test: ^0.12.0
